filebeat.inputs:
  - type: log
    paths:
      - /var/log/*.log # Chemin vers vos fichiers journaux, à adapter

output.elasticsearch:
  hosts: ["http://es-node-01:9200"] # Remplacez par l'adresse de votre noeud Elasticsearch
